navigation:
  - text: Home
    title: Home
    url: / 
  - text: About
    title: About
    url: /about/
  - text: Portfolio
    title: Portfolio
    url: /portfolio/
  - text: Contact
    title: Contact
    url: /contact/
  - text: Tags
    title: Tags
    url: /tags/

url: http://www.sasi-kala.com

markdown: redcarpet
exclude: ['README.md']
paginate: 5
paginate_path: "/blog/page/:num"
sass:
    sass_dir: _sass
    style: compressed

permalink: /blog/:title
gems:
 - jekyll-paginate
 - jekyll-sitemap

