navigation:
  - text: Home
    title: Home
    url: / 
  - text: About
    title: About
    url: /about.html 
  - text: Portfolio
    title: Portfolio
    url: /portfolio.html
  - text: Contact
    title: Contact
    url: /contact.html  

markdown: redcarpet
exclude: ['README.md']
sass:
    sass_dir: _sass
    style: compressed
