navigation:
  - text: Home
    title: Home
    url: / 
  - text: About
    title: About
    url: /about.html 
  - text: Portfolio
    title: Portfolio
    url: /portfolio.html
  - text: Archive
    title: Archive
    url: /archive.html  

markdown: redcarpet
baseurl: / 
exclude: ['README.md']
sass:
    sass_dir: _sass
    style: compressed
