navigation:
  - text: Blog
    title: Blog
    url: / 
  - text: Archive
    title: Archive
    url: /archives/
  - text: About
    title: About
    url: /about/
  - text: Portfolio
    title: Portfolio
    url: /portfolio/

url: http://www.sasi-kala.com

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: ['README.md']
paginate: 5
paginate_path: "/blog/page/:num"
sass:
  sass_dir: _sass
  style: compressed

permalink: /blog/:title
gems:
 - jekyll-paginate
 - jekyll-sitemap
collections:
- portfolios
